org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

# Environment Properties
minecraft_version=26.1
minecraft_version_range=[26.1]
neo_version=26.1.0.19-beta

## Mod Properties
mod_id=neovillagerswizard
mod_name=Neo Villagers - The wizard
mod_license=MIT
mod_version=1.12.6-26.1
mod_group_id=com.ryu.minecraft.mod.neoforge
mod_authors=Ryu78
mod_description=This mod adds a new villager the Wizard that trades items of nether, and has a table to recover the enchantments in books from items enchanted.