org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.7
parchment_mappings_version=2025.07.18

# Environment Properties
minecraft_version=1.21.7
minecraft_version_range=[1.21.7]
neo_version=21.7.25-beta

## Mod Properties
mod_id=neovillagerswizard
mod_name=Neo Villagers - The wizard
mod_license=MIT
mod_version=0.8.6-1.21.7
mod_group_id=com.ryu.minecraft.mod.neoforge
mod_authors=Ryu78
mod_description=This mod adds a new villager the Wizard that trades items of nether, and has a table to recover the enchantments in books from items enchanted.